apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: exemplars-app
  labels:
    name: exemplars-app
spec:
  selector:
    matchLabels:
      name: exemplars-app
  podMetricsEndpoints:
  - port: web
